name: deploy_prod

on:
    push:
        branches:
            - master

jobs:
    build:
        name: Build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v2
              with:
                  node-version: "12"
                  registry-url: "https://registry.npmjs.org"
            - name: Checkout Repo
              uses: actions/checkout@main
            - name: Install Dependencies
              run: npm install
            - name: Build
              run: npm run build -- --configuration production
            - name: Archive Production Artifact
              uses: actions/upload-artifact@master
              with:
                  name: dist
                  path: dist
    deploy_hosting:
        name: Deploy
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v2
              with:
                  node-version: "12"
                  registry-url: "https://registry.npmjs.org"
            - name: Checkout Repo
              uses: actions/checkout@master
            - name: Download Artifact
              uses: actions/download-artifact@master
              with:
                  name: dist
                  path: dist
            - name: Deploy to Firebase
              uses: w9jds/firebase-action@master
              with:
                  args: deploy --only hosting
              env:
                  FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
